application: designingforthefuture
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/queue/default
  script: task.py
- url: /dataloader
  script: dataloader.py
- url: /log_data
  script: task_log.py
- url: /_ah/mail/.+
  script: handle_email.py
- url: /.*
  script: runner.py

inbound_services:
- mail
  
builtins:
- datastore_admin: on
- remote_api: on

#skip_files: |
# ^bin/.*$|
# ^lib/python2.5/[^/]+$|
# ^(.*/)?(
# (app\.yaml)|
# (app\.yml)|
# (index\.yaml)|
# (index\.yml)|
# (#.*#)|
# (.*~)|
# (.*\.py[co])|
# (.*/RCS/.*)|
# (\..*)|
# )$
